version: "3.9"

services:
  
  server:
    image: eafxx/traktarr:latest
    container_name: traktarr_server
    configs:
      - source: server_config
        target: /config/config.json
    environment:
      DELAYL: 2.5	    
      SORT: rating
      NOSEARCH: yes
      NOTIFICATIONS: yes
      BLACKLIST: yes
      RUNNOW: no
      PGID: 1000
      PUID: 1000
      TZ: Europe/London
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - server_config:/config

networks:
  proxy:
    external: true

volumes:
  server_config:
    driver: local

configs:
  server_config:
    content: |
      {
        "automatic": {
          "movies": {
            "anticipated": 3,
            "boxoffice": 10,
            "interval": 20,
            "lists": {
              "https://trakt.tv/users/andronics/lists/movies-based-on-recently-watched-couchmoney-tv": 20,
              "https://trakt.tv/users/andronics/lists/movies-recommendations-couchmoney-tv": 20,
              "https://trakt.tv/users/benfranklin/lists/best-mindfucks": 20,
              "https://trakt.tv/users/kcador/recommendations": 20,
              "https://trakt.tv/users/zyrus/lists/80s-classics": 20
            },
            "popular": 3,
            "trending": 3
          },
          "shows": {
            "anticipated": 10,
            "interval": 48,
            "lists": {
              "https://trakt.tv/users/andronics/lists/tv-based-on-recently-watched-couchmoney-tv": 20,
              "https://trakt.tv/users/andronics/lists/tv-recommendations-couchmoney-tv": 20,
              "https://trakt.tv/users/benfranklin/lists/best-mindfucks": 20,
              "https://trakt.tv/users/kcador/recommendations": 20
            },
            "popular": 1,
            "trending": 1
          }
        },
        "core": {
          "debug": true
        },
        "filters": {
          "movies": {
            "allowed_countries": [
              "us",
              "ca",
              "gb",
              "au",
              "nz"
            ],
            "allowed_languages": [
              "en"
            ],
            "blacklisted_genres": [
              "documentary",
              "music"
            ],
            "blacklisted_max_runtime": 0,
            "blacklisted_max_year": 2024,
            "blacklisted_min_runtime": 60,
            "blacklisted_min_year": 1960,
            "blacklisted_title_keywords": [],
            "blacklisted_tmdb_ids": [],
            "disabled_for": [],
            "rotten_tomatoes": "30"
          },
          "shows": {
            "allowed_countries": [
              "us",
              "ca",
              "gb",
              "au",
              "nz",
              "ie"
            ],
            "allowed_languages": [
              "en"
            ],
            "blacklisted_genres": [
              "animation",
              "game-show",
              "talk-show",
              "home-and-garden",
              "children",
              "reality",
              "anime",
              "news",
              "documentary",
              "special-interest"
            ],
            "blacklisted_max_runtime": 0,
            "blacklisted_max_year": 2023,
            "blacklisted_min_runtime": 15,
            "blacklisted_min_year": 1980,
            "blacklisted_networks": [],
            "blacklisted_title_keywords": [
              "WWE"
            ],
            "blacklisted_tvdb_ids": [
              71091,
              74467,
              296861,
              78804,
              229331,
              425498,
              434749,
              320206,
              368768,
              72757,
              71862,
              264234,
              394331
            ],
            "disabled_for": []
          }
        },
        "notifications": {
          "verbose": true
        },
        "omdb": {
          "api_key": "${TRAKTARR_OMDB_API_KEY:-super_secret_omdb_api_key}"
        },
        "radarr": {
          "api_key": "${TRAKTARR_RADARR_API_KEY:-super_secret_radarr_api_key}",
          "minimum_availability": "released",
          "quality": "HD-720p",
          "root_folder": "/mnt/media/movies/",
          "url": "http://radarr_server:7878/"
        },
        "sonarr": {
          "api_key": "${TRAKTARR_SONARR_API_KEY:-super_secret_sonarr_api_key}",
          "language": "English",
          "quality": "HD-720p",
          "root_folder": "/mnt/media/tv/",
          "season_folder": true,
          "tags": [
            "trakt"
          ],
          "url": "http://sonarr_server:8989/"
        },
        "trakt": {
          "${TRAKTARR_TRAKT_USER_LOGIN:-super_secret_trakt_user_login}": {
            "access_token": "${TRAKTARR_TRAKT_USER_ACCESS_TOKEN:-super_secret_trakt_user_access_token}",
            "created_at": 1712058532,
            "expires_in": 7776000,
            "refresh_token": "${TRAKTARR_TRAKT_USER_REFRESH_TOKEN:-super_secret_trakt_user_refresh_token}",
            "scope": "public",
            "token_type": "Bearer"
          },
          "client_id": "${TRAKTARR_TRAKT_CLIENT_ID:-super_secret_trakt_client_id}",
          "client_secret": "${TRAKTARR_TRAKT_CLIENT_SECRET-super_secret_trakt_client_secret}"
        }
      }
    

      
      