version: "3.9"

services:
  
  exporter:
    image: ghcr.io/onedr0p/exportarr:v1.6.0
    container_name: prowlarr_exporter
    command: ["prowlarr"]
    environment:
      APIKEY: ${PROWLARR_API_KEY:-super_secret_api_key}
      PORT: 9990
      URL: "http://prowlarr_server:${PROWLARR_PORT:-9696}"
    networks:
      - backend
    restart: unless-stopped

  server:
    image: ghcr.io/linuxserver/prowlarr:latest
    container_name: prowlarr_server
    configs:
      - source: server_config
        target: /config/config.xml
    environment:
      AUTO_UPDATE: true
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entrypoints: https-internal,https-external
      traefik.http.services.prowlarr.loadbalancer.passHostHeader: true
    networks:
      - backend
      - proxy
      - tor
      - vpn
    restart: unless-stopped
    volumes:
      - server_config:/config

networks:
  backend:
    external: true
  proxy:
    external: true
  tor:
    external: true
  vpn:
    external: true
    
volumes:
  server_config:
    driver: local

configs:
  server_config:
    content: |
      <Config>
        <ApiKey>${PROWLARR_API_KEY:-super_secret_api_key}</ApiKey>
        <Port>${PROWLARR_PORT:-9696}</Port>
        <LogLevel>${PROWLARR_LOG_LEVEL:-info}</LogLevel>
        <AuthenticationMethod>External</AuthenticationMethod>
        <AuthenticationRequired>Enabled</AuthenticationRequired>
      </Config>
