version: "3"

services:
  
  server:
    image: ghcr.io/linuxserver/code-server:latest
    container_name: code_server
    configs:
      - source: server_user_settings
        target: /config/data/User/settings.json
    environment:
      AUTO_UPDATE: true
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:universal-tshoot|linuxserver/mods:code-server-golang|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-extension-arguments
      PUID: 1000
      PGID: 1000
      SUDO_PASSWORD: ${CODE_SUDO_PASSWORD:-super_secret_sudo_password}
      VSCODE_EXTENSION_IDS: catppuccin.catppuccin-vsc|ms-azuretools.vscode-docker|piousdeer.adwaita-theme
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.code.entrypoints: https-internal,https-external
      traefik.http.services.code.loadbalancer.passHostHeader: true
    networks:
      - backend
      - proxy
    restart: unless-stopped
    volumes:
      - server_config:/config
      - /mnt:/mnt
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  backend:
    external: true
  proxy:
    external: true

volumes:
  server_config:
    driver: local

configs:
  server_user_settings:
    content: |  
      {
          "workbench.colorTheme": "Catppuccin Macchiato",
          "workbench.productIconTheme": "adwaita",
          "workbench.iconTheme": null
      }