version: "3.9"

services:
  
  server:
    image: jeroenslot/nordvpn-proxy:latest
    container_name: nordvpn_server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 1.1.1.1
      - 8.8.4.4
      - 8.8.8.8
    env_file:
      - .env
    environment:
      COUNTRY: ${NORDVPN_COUNTRY:-"GB"}
      LOCAL_NETWORK: ${NORDVPN_LOCAL_NETWORK:-"172.16.0.0/20"}
      PASSWORD: ${NORDVPN_PASSWORD:-"super_secret_password"}
      USERNAME: ${NORDVPN_USERNAME:-"super_secret_username"}
    healthcheck:
      test: ["CMD-SHELL","echo", "1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - vpn
    ports:
      - 8118:8118
    restart: unless-stopped
    volumes:
      - server_config:/app/ovpn/config
      - /etc/localtime:/etc/localtime:ro

networks:
  vpn:
    external: true

volumes:
  server_config:
    driver: local