services:

  mariadb:
    image: mariadb
    container_name: vaultwarden_mariadb
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-super_secret_root_password}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD:-super_secret_password}
      MYSQL_DATABASE: ${MARIADB_DATABASE:-super_secret_database}
      MYSQL_USER: ${MARIADB_USER:-super_secret_user}
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  
  server:
    image: vaultwarden/server:latest
    container_name: vaultwarden_server
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN:-super_secret_admin_token}
      DOMAIN: "https://vaultwarden.andronics.io"
      DATABASE_URL: "mysql://${MARIADB_USER:-super_secret_user}:${MARIADB_PASSWORD:-super_secret_password}@mariadb/${MARIADB_DATABASE:-super_secret_database}"
      EXTENDED_LOGGING: true
      LOG_FILE: /var/log/vaultwarden/access.log
      LOG_LEVEL: debug
      SIGNUPS_ALLOWED: true
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entrypoints: https-internal
      traefik.http.services.vaultwarden.loadbalancer.passHostHeader: true
    networks:
      - backend
      - proxy
    restart: unless-stopped
    volumes:
      - server_data:/data
      - server_log:/var/log/vaultwarden

networks:
  backend:
    external: true
  proxy:
    external: true

volumes:
  mariadb_data:
    driver: local
  server_data:
    driver: local
  server_log:
    driver: local
