version: "3.9"

services:
  
  server:
    image: golift/unpackerr
    container_name: unpackerr_server
    configs:
      - source: server_config
        target: /config/unpackerr.conf
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.unpackerr.entrypoints: https-internal,https-external
      traefik.http.services.unpackerr.loadbalancer.passHostHeader: true
      traefik.http.services.unpackerr.loadbalancer.server.port: 5656
    networks:
      - backend
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    volumes:
      - server_config:/config
      - /mnt/transfer:/mnt/transfer
 
networks:
  backend:
    external: true
  proxy:
    external: true

volumes:
  server_config:
    driver: local

configs:
  server_config:
    content: |
      debug = true
      quiet = false
      error_stderr = false
      activity = false
      log_queues = "1m"
      log_files = 10
      log_file_mb = 10
      interval = "2m"
      start_delay = "1m"
      retry_delay = "5m"
      parallel = 1
      file_mode = "0644"
      dir_mode = "0755"

      [[folder]]
      path = '/mnt/transfer/complete/seedbox'
      extract_path = ""
      delete_after = "0"
      disable_recursion = false
      delete_files = false
      delete_original = false
      disable_log = false
      move_back = false
      extract_isos = false

      [[lidarr]]
      url = "http://lidarr_server:8686"
      api_key = "${UNPACKERR_LIDARR_API_KEY:-super_secret_lidarr_api_key}"
      paths = ['/mnt/transfer/complete/music']
      protocols = "torrent"

      [[radarr]]
      url = "http://radarr_server:7878"
      api_key = "${UNPACKERR_RADARR_API_KEY:-super_secret_radarr_api_key}"
      paths = ['/mnt/transfer/complete/movies']
      protocols = "torrent"

      [[readarr]]
      url = "http://readarr_server:8878"
      api_key = "${UNPACKERR_READARR_API_KEY:-super_secret_readarr_api_key}"
      paths = ['/mnt/transfer/complete/books']
      protocols = "torrent"

      [[sonarr]]
      url = "http://sonarr_server:8989"
      api_key = "${UNPACKERR_SONARR_API_KEY:-super_secret_sonarr_api_key}"
      paths = ['/mnt/transfer/complete/tv']
      protocols = "torrent"

      [webserver]
      metrics = true
      listen_addr = "0.0.0.0:5656"
      urlbase = "/"
