version: "3.9"

services:

  exporter:
    image: bagul/goemby_exporter:latest
    container_name: emby_exporter
    environment:
      CONFIG_FILE: /config/exporter.yml
      TZ: Europe/London
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - ./volumes/config:/config
  
  server:
    image: ghcr.io/linuxserver/emby:latest
    container_name: emby_server
    devices:
      - /dev/fuse
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.http.routers.emby.entrypoints: https-internal,https-external
      traefik.http.services.emby.loadbalancer.passHostHeader: true
    networks:
      - backend
      - proxy
    ports: 
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
    volumes:
      - server_backup:/backup
      - server_config:/config
      - /.pool/cloud/media:/.pool/cloud/media
      - /.pool/nvme/media:/.pool/nvme/media
      - /.vfs/media:/.vfs/media
      - /mnt/media:/mnt/media

networks:
  backend:
    external: true
  proxy:
    external: true

volumes:
  server_backup:
    driver: local
  server_config:
    driver: local