services:
  
  server:
    image: binwiederhier/ntfy
    container_name: ntfy_server
    command:
      - serve
    configs:
      - source: server_config
        target: /etc/ntfy/server.yml
    environment:
      TZ: Europe/London
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      traefik.enable: true
      traefik.http.routers.ntfy.entrypoints: https-internal,https-external
      traefik.http.services.ntfy.loadbalancer.passHostHeader: true
    networks:
      - backend
      - proxy
    restart: unless-stopped
    volumes:
      - server_cache:/var/cache/ntfy
      - server_lib:/var/lib/ntfy
      - server_log:/var/log/ntfy

networks:
  backend:
    external: true
  proxy:
    external: true

volumes:
  server_cache:
    driver: local
  server_lib:
    driver: local
  server_log:
    driver: local

configs:
    server_config:
        content: |
          attachment-cache-dir: /var/lib/cache/attachments
          attachment-total-size-limit: "200M"
          attachment-file-size-limit: "15M"
          attachment-expiry-duration: "96h"
          auth-file: /var/lib/ntfy/user.db
          auth-default-access: "deny-all"
          auth-startup-queries: |
            pragma journal_mode = WAL;
            pragma synchronous = normal;
            pragma temp_store = memory;
            pragma busy_timeout = 15000;
            vacuum;
          base-url: https://ntfy.andronics.io
          behind-proxy: true
          cache-file: /var/cache/ntfy/cache.db
          cache-duration: "96h"
          cache-startup-queries: |
            pragma journal_mode = WAL;
            pragma synchronous = normal;
            pragma temp_store = memory;
            pragma busy_timeout = 15000;
            vacuum;
          enable-metrics: true
          enable-signup: false
          enable-login: false
          enable-reservations: true
          log-level: trace
          log-format: text
          log-file: /var/log/ntfy/ntfy.log
          smtp-server-listen: :25
          smtp-server-domain: nfty.andronics.io
          upstream-base-url: https://ntfy.sh
          web-root: /