version: "3"

services:
  
  server:
    image: pihole/pihole:latest
    container_name: pihole_server
    cap_add:
      - NET_ADMIN
    configs:
      - source: server_wildcard_dns
        target: /etc/dnsmasq.d/10-wildcard-dns.conf
    env_file:
      - .env
    environment:
      DNSMASQ_LISTENING: 'all'
      TZ: Europe/London
      VIRTUAL_HOST: pihole.andronics.io
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD:-"super_secret_webpassword"}
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.entrypoints: https-internal,https-external
      traefik.http.services.pihole.loadbalancer.passHostHeader: true
      traefik.http.services.pihole.loadbalancer.server.port: 80
      
    networks:
      - proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    restart: unless-stopped
    volumes:
      - server_config:/etc/pihole
      - server_cache:/etc/dnsmasq.d

networks:
  proxy:
    external: true
    
volumes:
  server_cache:
    driver: local
  server_config:
    driver: local

configs:
  server_wildcard_dns:
    content: |
      address=/andronics.io/192.168.0.1
