version: "3.9"

services:
  
  server:
    image: traefik:latest
    command:
      - '--configfile=/etc/traefik.yml'
    container_name: traefik_server
    configs:
      - source: server_config
        target: /etc/traefik.yml
      - source: server_dynamic_authelia
        target: /etc/traefik.d/authelia.yml
      - source: server_dynamic_authentik
        target: /etc/traefik.d/authentik.yml
      - source: server_dynamic_crowdsec
        target: /etc/traefik.d/crowdsec.yml
      - source: server_dynamic_themes
        target: /etc/traefik.d/themes.yml
    extra_hosts:
      - host.docker.internal:172.17.0.1
    labels:
      com.centurylinklabs.watchtower.enable: false
      traefik.enable: true
      traefik.http.routers.traefik.entrypoints: https-internal,https-external
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.traefik.loadbalancer.passHostHeader: true
    networks:
      - backend
      - proxy
    ports: 
      - 25:25         # smtp-internal
      - 80:80         # http-internal
      - 443:443       # https-internal
      - 10080:10080   # http-external
      - 10443:10443   # https-external
      - 13389:13389   # rdp-external
      - 27017:27017   # mongodb-internal
      - 51820:51820   # wireguard-external
      - 58846:58846   # deluge-internal
    restart: unless-stopped
    security_opt:
      - "no-new-privileges=true"
    volumes:
      - server_data:/var/lib/traefik
      - server_log:/var/log/traefik
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  backend:
    external: true
  proxy:
    external: true
    
volumes:
  server_data:
    driver: local
  server_log:
    driver: local


configs:

  server_config:
    content: |
      accessLog:
        filePath: /var/log/traefik/access.log
        format: common
      api:
        insecure: true
        dashboard: true
        debug: true
      certificatesResolvers:
        production:
          acme:
            caServer: https://acme-v02.api.letsencrypt.org/directory
            email: "andronics@gmail.com"
            storage: "/var/lib/traefik/certificates/production.json"
            httpChallenge:
              entryPoint: http-external
            tlsChallenge:
        staging:
          acme:
            caServer: https://acme-staging-v02.api.letsencrypt.org/directory
            email: "andronics@gmail.com"
            storage: "/var/lib/traefik/certificates/staging.json"
            httpChallenge:
              entryPoint: http-external
            tlsChallenge:
      entryPoints:
        deluge:
          address: :58846/tcp
        mongodb:
          address: :27017
        metrics:
          address: :8002
        rdp:
          address: :3389/tcp
        smtp:
          address: :25/tcp
        http-external:
          address: :10080/tcp
          forwardedHeaders:
            insecure: true
          http:
            middlewares:
              - crowdsec-bouncer@file
            redirections:
              entryPoint:
                scheme: https
                to: https-external
        http-internal:
          address: :80/tcp
          http:
            middlewares:
              - crowdsec-bouncer@file
            redirections:
              entryPoint:
                scheme: https
                to: https-internal
        https-external:
          address: :10443/tcp
          forwardedHeaders:
            insecure: true
          http:
            middlewares:
              - authelia@file
              - crowdsec-bouncer@file
            tls:
              certResolver: production
        https-internal:
          address: :443/tcp
          http:
            middlewares:
              - authelia@file
              - crowdsec-bouncer@file
            tls:
              certResolver: production
        wireguard:
          address: :51820/udp
      experimental:
        plugins:
          theme-park:
            modulename: "github.com/packruler/traefik-themepark"
            version: "v1.2.2"
      global:
        checkNewVersion: false
        sendAnonymousUsage: false
      log:
        filePath: /var/log/traefik/traefik.log
        format: common
        level: ERROR
      metrics:
        prometheus:
          addEntryPointsLabels: true
          addRoutersLabels: true
          addServicesLabels: true
          entryPoint: metrics
          headerLabels:
            apikey: x-api-key
            useragent: User-Agent
      providers:
        docker:
          defaultRule: "Host(`{{ index .Labels \"com.docker.compose.project\" }}.andronics.io`)"
          exposedByDefault: false
          network: proxy
          watch: true
        file:
          directory: /etc/traefik.d
          watch: true
      serversTransport:
        insecureSkipVerify: true
  server_dynamic_authelia:
    content: |
      http:
        middlewares:
          authelia:
            forwardAuth:
              address: http://authelia_server:9091/api/verify?rd=https://auth.andronics.io
              trustForwardHeader: true
              authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
  server_dynamic_authentik:
    content: |
      http:
        middlewares:
            authentik:
                forwardAuth:
                    address: http://authentik_server:9000/outpost.goauthentik.io/auth/traefik
                    trustForwardHeader: true
                    authResponseHeaders:
                        - X-authentik-username
                        - X-authentik-groups
                        - X-authentik-email
                        - X-authentik-name
                        - X-authentik-uid
                        - X-authentik-jwt
                        - X-authentik-meta-jwks
                        - X-authentik-meta-outpost
                        - X-authentik-meta-provider
                        - X-authentik-meta-app
                        - X-authentik-meta-version
  server_dynamic_crowdsec:
    content: |
      http:
        middlewares:
            crowdsec-bouncer:
                forwardAuth:
                    address: http://traefik_bouncer:8080/api/v1/forwardAuth
                    trustForwardHeader: true
  server_dynamic_themes:
    content: |
      http:
        middlewares:
          theme-lidarr:
            plugin:
              themepark:
                app: lidarr
                theme: dark
                addons:
                  - 4k-logo
                  - darker
          theme-prowlarr:
            plugin:
              themepark:
                app: prowlarr
                theme: dark
                addons:
                  - 4k-logo
                  - darker
          theme-radarr:
            plugin:
              themepark:
                app: radarr
                theme: dark
                addons:
                  - 4k-logo
                  - darker
          theme-readarr:
            plugin:
              themepark:
                app: readarr
                theme: dark
                addons:
                  - 4k-logo
                  - darker
          theme-sonarr:
            plugin:
              themepark:
                app: sonarr
                theme: dark
                addons:
                  - 4k-logo
