version: "3.9"

services:
  
  server:
    image: b4bz/homer:latest
    container_name: homer_server
    environment:
      UID: 1000
      GID: 1000
    labels:
      traefik.enable: true
      traefik.http.routers.homer.entrypoints: https-internal,https-external
      traefik.http.routers.homer.rule: Host(`andronics.io`)
      traefik.http.services.homer.loadbalancer.passHostHeader: true
      traefik.http.services.homer.loadbalancer.server.port: 8080
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - server_data:/www/assets

networks:
  proxy:
    external: true

volumes:
  server_data:
    driver: local