version: "3.9"

services:

  server:
    image: ghcr.io/linuxserver/deluge:latest
    container_name: deluge_server
    configs:
      - source: server_auth
        target: /config/auth
      - source: server_autoadd
        target: /config/autoadd.conf
      - source: server_core
        target: /config/core.conf
      - source: server_label
        target: /config/label.conf
    environment:
      DELUGE_LOGLEVEL: ${DELUGE_LOG_LEVEL:-debug}
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    labels:
      traefik.enable: true
      traefik.tcp.routers.deluge.entrypoints: deluge
      traefik.tcp.routers.deluge.rule: HostSNI(`*`)
      traefik.tcp.routers.deluge.service: deluge
      traefik.tcp.services.deluge.loadbalancer.server.port: 58846
    networks:
      - proxy
      - backend
    restart: unless-stopped
    volumes:
      - server_config:/config
      - /mnt/transfer:/mnt/transfer

  webui:
    image: ghcr.io/relvacode/storm:latest
    container_name: deluge_webui
    depends_on:
      - server
    env_file:
      - .env
    environment:
      DELUGE_RPC_HOSTNAME: deluge_server
      DELUGE_RPC_PASSWORD: ${DELUGE_RPC_PASSWORD:-super_secret_rpc_password}
      DELUGE_RPC_USERNAME: ${DELUGE_RPC_USERNAME:-super_secret_rpc_username}
      DELUGE_RPC_VERSION: v2
    labels:
      traefik.enable: true
      traefik.http.routers.deluge.entrypoints: https-internal,https-external
      traefik.http.services.deluge.loadbalancer.passHostHeader: true
      traefik.http.services.deluge.loadbalancer.server.port: 8221
    networks:
      - proxy
    restart: unless-stopped

networks:
  backend:
    external: true
  proxy:
    external: true

volumes:    
  server_config:
      driver: local

configs:
  server_auth:
    content: |
      localclient:${DELUGE_RPC_PASSWORD:-super_secret_rpc_password}:10
      ${DELUGE_RPC_USERNAME:-super_secret_rpc_username}:${DELUGE_RPC_PASSWORD:-super_secret_rpc_password}:10
  server_autoadd:
    content: |
      {
          "file": 2,
          "format": 1
      }{
          "next_id": 2,
          "watchdirs": {
              "1": {
                  "abspath": "/mnt/transfer/autoload",
                  "add_paused": true,
                  "add_paused_toggle": true,
                  "append_extension": ".added",
                  "append_extension_toggle": true,
                  "enabled": true,
                  "path": "/mnt/transfer/autoload"
              }
          }
      }
  server_core:
    content: |
      {
          "file": 1,
          "format": 1
      }{
          "add_paused": true,
          "allow_remote": true,
          "download_location": "/mnt/transfer/incomplete",
          "enabled_plugins": [
              "Label",
              "AutoAdd",
              "Toggle",
              "ltConfig"
          ],
          "geoip_db_location": "/usr/share/GeoIP/GeoIP.dat",
          "max_active_downloading": 20,
          "max_active_limit": 100,
          "max_active_seeding": 80,
          "max_connections_global": -1,
          "max_connections_per_second": 20,
          "max_connections_per_torrent": -1,
          "max_download_speed": -1.0,
          "max_download_speed_per_torrent": -1,
          "max_half_open_connections": 250,
          "max_upload_slots_global": 4,
          "max_upload_slots_per_torrent": -1,
          "max_upload_speed": -1.0,
          "max_upload_speed_per_torrent": -1,
          "move_completed": true,
          "move_completed_path": "/mnt/transfer/complete",
          "remove_seed_at_ratio": false,
          "seed_time_limit": 1440,
          "seed_time_ratio_limit": 7.0,
          "share_ratio_limit": 2.0,
          "stop_seed_at_ratio": true,
          "stop_seed_ratio": 3.0,
          "torrentfiles_location": "/mnt/transfer/torrents"
      }
  server_label:
    content: |
      {
          "file": 1,
          "format": 1
      }{
          "labels": {
              "audiobooks": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/audiobooks"
              },
              "ebooks": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/ebooks"
              },
              "games": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/games"
              },
              "movies": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/movies"
              },
              "music": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/music"
              },
              "seedbox": {
                  "auto_add": true,
                  "auto_add_trackers": [
                      "http://td.jumbohostpro.eu,https://sync.td-peers.com"
                  ],
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/seedbox"
              },
              "software": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/software"
              },
              "standup": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/standup"
              },
              "tv": {
                  "move_completed": true,
                  "move_completed_path": "/mnt/transfer/complete/tv"
              }
          },
          "torrent_labels": {}
      }