version: "3.9"

services:
  
  server:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr_server
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      TZ: Europe/London
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    external: true