version: "3.9"

services:

  traefik_bouncer:
    image: fbonalair/traefik-crowdsec-bouncer:latest
    container_name: crowdsec_traefik_bouncer
    depends_on:
      - server
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY:-super_secret_api_key} # docker exec crowdsec_server cscli bouncers add traefik_bouncer
      CROWDSEC_AGENT_HOST: crowdsec_server:8080
    networks:
      - backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  
  server:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec_server
    configs:
      - source: server_acquis
        target: /etc/crowdsec/acquis.yaml
    environment:
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik Dominic-Wagner/vaultwarden LePresidente/authelia"
      GID: "${GID-1000}"
    networks:
      - backend
      - proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    volumes:
      - authelia_server_log:/var/log/authelia
      - server_config:/etc/crowdsec
      - server_data:/var/lib/crowdsec
      - traefik_server_log:/var/log/traefik
      - vaultwarden_server_log:/var/log/vaultwarden
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  backend:
    external: true
  proxy:
    external: true
    
volumes:
  authelia_server_log:
    external: true
  server_config:
    driver: local
  server_data:
    driver: local
  traefik_server_log:
    external: true
  vaultwarden_server_log:
    external: true

configs:
  server_acquis:
    content: |
      filenames:
        - /var/log/authelia/*
      labels:
        type: authelia
      ---
      filenames:
        - /var/log/traefik/*
      labels:
        type: traefik
      ---
      filenames:
        - /var/log/vaultwarden/*
      labels:
        type: Vaultwarden



